import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '../../components/navbar'



export const metadata = {
  title: 'WorkClock',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <div className="nav">
          <Navbar />
        </div>

        <div className="main">{children}</div>

        <div className="footer"></div>
      </body>
    </html>
  )
}
